'use client'
import ContactFormArea from '@/components/Contact/ContactFormArea';
import ContactInfo from '@/components/Contact/ContactInfo';
import DrawerHeader from '@/components/Drawer&HeaderCom/drawerheaderclient';
// import Drawer from '@/components/Layout/Drawer/Drawer';
import Footer from '@/components/Layout/Footer/Footer';
import FooterCopyright from '@/components/Layout/Footer/FooterCopyright';
// import Header from '@/components/Layout/Header/Header';
// import Layout from '@/components/Layout/Layout';
// import useToggle from '@/Hooks/useToggle';
import React from 'react';
// import RootLayout from '../layout'

// export const metadata = {
//   title: 'Contact App',
//   description: 'Generated by create next app',
// }


export default function Contact() {

  return (

      <div className="home-1-bg">
      
        <DrawerHeader />
        <ContactInfo />
        <ContactFormArea />
        <Footer />
        <FooterCopyright />
      </div>

  );
}
